daychangers/urls.py
from django.conf.urls import url
from . import views
app_name = 'daychangers'

urlpatterns = [
	url(r'^$',views.login_user, name='login_user'),
    url(r'^index/$', views.index, name='index'),
    url(r'^register/$',views.register, name='register'),     
    url(r'^data/$',views.data, name='data'),
    url(r'^checkorder/$',views.checkorder, name='checkorder'),
    url(r'^addsymbol/$',views.addsymbol, name='addsymbol'),
    url(r'^holding/$',views.holding, name='holding'),
    url(r'^login/$',views.login_user, name='login_user'),
    url(r'^orders/$',views.orders, name='orders'),
    url(r'^logout/$',views.logout_user, name='logout_user'),
]

nse/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('daychangers.urls') ),
]

daychangers/models.py
from django.db import models
from django.contrib.auth.models import Permission, User

# Create your models here.
class Orderbook(models.Model):
	client_id=models.CharField(max_length=100)
	symbol = models.CharField(max_length=250)
	price =models.DecimalField(max_digits=7, decimal_places=2)
	quantity = models.IntegerField()
	date =models.DateTimeField()
	trade_type=models.CharField(max_length=250)
	orderno=models.IntegerField()
	ordertype=models.CharField(max_length=100)
	status=models.CharField(max_length=100)
	
	def __str__(self):
		return  self.client_id
		
class Pendingorder(models.Model):
	client_id=models.CharField(max_length=100)
	symbol = models.CharField(max_length=250)
	price =models.DecimalField(max_digits=7, decimal_places=2)
	quantity = models.IntegerField()
	date =models.DateTimeField()
	trade_type=models.CharField(max_length=250)
	orderno=models.IntegerField()
	ordertype=models.CharField(max_length=100)
	status=models.CharField(max_length=100)		

	def __str__(self):
		return  self.client_id		

class Stockspecific(models.Model):
	orderdetail = models.ForeignKey(Orderbook,null=True)
	symbol = models.CharField(max_length=250)
	price =models.DecimalField(max_digits=7, decimal_places=2)
	quantity = models.IntegerField(null=True)	
	total=models.IntegerField(null=True)

	def __str__(self):
		return  self.symbol

class Margin(models.Model):
	user=models.CharField(max_length=100)
	funds=models.DecimalField(max_digits=9, decimal_places=2)
	holdings=models.DecimalField(max_digits=9, decimal_places=2)

	def __str__(self):
		return  self.user
		
class Stocksearch(models.Model):
	name=models.CharField(max_length=20)

class Ordernumber(models.Model):
	number=models.IntegerField()

	def __str__(self):
		return  str(self.number)

class Addedscript(models.Model):
	user=models.CharField(max_length=100)
	name=models.CharField(max_length=20,null=True)
	ltp=models.DecimalField(max_digits=9, decimal_places=2)

	def __str__(self):
		return  self.name

daychangers/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

class UserForm(forms.ModelForm):
	password =forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields =['username','email','password']

daychangers/views.py
from django.shortcuts import render
from .nse import Nse
from urllib.request import build_opener, HTTPCookieProcessor, Request
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,redirect
from django.http import Http404
from django.contrib.auth import authenticate, login,logout
from django.views import generic 
from django.views.generic import View
from django.contrib.sessions.backends.db import SessionStore
from .forms import UserForm
from .models import Orderbook
from .models import Ordernumber
from .models import Stockspecific
from .models import Margin
from .models import Stocksearch
from .models import Addedscript
from .models import Pendingorder
from urllib.parse import urlencode
import requests
import json
import pytz
import collections
import datetime
import decimal
import csv
import datetime

def index(request):
    """
        return: send the user to the login page after login
    """
    nse = Nse()
    gainer=nse.get_top_gainers()
    loser=nse.get_top_losers()
    username = request.user
    mar=Margin.objects.filter(user=username)
    script=Addedscript.objects.filter(user=username)
    return render(request, 'daychangers/dashboard.html',{'gainer':gainer, 'loser':loser,'margin':mar,'user':username,'script':script} )    

def register(request):
    """
        Register the client and allot margin of 1 lakh initially
        Saving one script initially on all client register, so exception is not raised 
    """
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        nse = Nse()
        user.save()
        fund_available=Margin(funds=100000,user=username,holdings=0)
        fund_available.save()
        detail=nse.get_quote("SBIN")
        add=Addedscript(name="SBIN",user=username,ltp=detail['lastPrice'])
        add.save()
        return render(request, 'daychangers/redlogin.html')
    context = {
            "form": form,
        }
    return render(request, 'daychangers/registration_form.html',{'form': form,} )    

def login_user(request):
    """
       Authenticating the user login using django authenticate 
    """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)  
            request.session['user_name']=username
            mar=Margin.objects.filter(user=username)
            nse=Nse()
            gainer=nse.get_top_gainers()
            loser=nse.get_top_losers()
            return redirect('http://gainerandloser.herokuapp.com/index/')

        else:    
            return render(request, 'daychangers/login.html',{'error_message': 'Go and Create new account'})   

    else:   
        return render(request, 'daychangers/login.html')  

def logout_user(request):
    """
       Deleting the session login  
    """
    logout(request) 
    return render(request, 'daychangers/login.html')
            
def checkorder(request):
    """
       Order placement module, storing the detail in orderbook models  
    """
            if request.method == "POST":        
                stock_name= request.POST['place']

            if request.method=="POST":
                qua=request.POST['quantity']

            if request.method=="POST":
                ortype=request.POST['order']       

            nse=Nse()
            getquote=nse.get_quote(stock_name)
            order_number=Ordernumber.objects.all()
            for ord in order_number:
                ordr=ord
                order_no=ord.number+1
            user = request.user
            if ortype == "market":
                order= Orderbook(client_id=user,symbol=stock_name,price=getquote['lastPrice'],quantity=1,date=datetime.datetime.now(tz=pytz.timezone('Asia/Calcutta')),trade_type='BUY',orderno=order_no,ordertype=ortype, status="success")
                order.save()

            else:    
                if float(qua) >= getquote['lastPrice']:
                    order= Orderbook(client_id=user,symbol=stock_name,price=qua,quantity=1,date=datetime.datetime.now(tz=pytz.timezone('Asia/Calcutta')),trade_type='BUY',orderno=order_no,ordertype=ortype, status="success")
                    order.save()
                else:
                    order= Pendingorder(client_id=user,symbol=stock_name,price=qua,quantity=1,date=datetime.datetime.now(tz=pytz.timezone('Asia/Calcutta')),trade_type='BUY',orderno=order_no,ordertype=ortype,status="pending")
                    order.save()

            number=Ordernumber(number=order_no)
            number.save()
            holding_value = getquote['lastPrice']*1
            detail=Margin.objects.filter(user=user)
            q=Orderbook.objects.filter(client_id=user)
            q1=Pendingorder.objects.filter(client_id=user)
            for checks in q1:
                if checks.status == "pending":
                    sym=nse.get_quote(checks.symbol)
                    if checks.price >= decimal.Decimal(sym['lastPrice']):
                        order= Orderbook(client_id=user,symbol=checks.symbol,price=sym['lastPrice'],quantity=1,date=datetime.datetime.now(tz=pytz.timezone('Asia/Calcutta')),trade_type='BUY',orderno=order_no,ordertype=ortype, status="success")
                        order.save()
                        move=Pendingorder.objects.filter(client_id=user,symbol=checks.symbol)
                        move.delete()


            for inspect in detail:
                fund_update=decimal.Decimal(inspect.funds) - decimal.Decimal(holding_value)
                holdingval=decimal.Decimal(100000) - decimal.Decimal(fund_update)
                Margin.objects.filter(user=user).update(holdings=holdingval,funds=fund_update)
            return redirect('https://gainerandloser.herokuapp.com/orders') 
def orders(request):
    """
       This page keep on refreshing as per ajax request, and convert the pending order to completed
       order, as per order type 
    """
        user = request.user
        nse=Nse()
        q=Orderbook.objects.filter(client_id=user)
        q1=Pendingorder.objects.filter(client_id=user)
        order_number=Ordernumber.objects.all()
        for ord in order_number:
                ordr=ord.number

        for checks in q1:
            if checks.status == "pending":
                sym=nse.get_quote(checks.symbol)
                if checks.price >= decimal.Decimal(sym['lastPrice']):
                    order= Orderbook(client_id=user,symbol=checks.symbol,price=sym['lastPrice'],quantity=1,date=datetime.datetime.now(tz=pytz.timezone('Asia/Calcutta')),trade_type='BUY',orderno= ordr,ordertype="limit", status="success")
                    order.save()
                    move=Pendingorder.objects.filter(client_id=user,symbol=checks.symbol)
                    move.delete()
                  
        return render(request, 'daychangers/logtest.html',{'i_d':q,'q1':q1,})




def addsymbol(request): 
    """
       Add the script in real time to marketwatch 
    """
    stock=request.GET['stock']
    nse=Nse()
    user = request.user
    detail=nse.get_quote(stock)
    add=Addedscript(name=stock,user=user,ltp=detail['lastPrice'])
    add.save() 
    return HttpResponse(detail['lastPrice'])

def holding(request):  
    """
       retrives the holding from orderbook 
    """
    nse=Nse()   
    user = request.user
    hold=Orderbook.objects.filter(client_id=user) 
    if hold:
        for detail in hold: 
            detail=nse.get_quote(detail.symbol)
            return render(request, 'daychangers/holding.html',{'i_d':hold,'detail':detail})  
    else:
        return render(request, 'daychangers/holding.html',{'msg':'no holdings'},)                                   

daychangers/templates/daychangers/dashboard.html
<html>
<head>
{% include 'meta/meta.html' %}
<link rel="icon" href="https://support.zerodha.com/logo.php">
</head>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 <style>
 .location {
   position: absolute;
   left:40%;
   top: 05%;
}
#shift{
  position: absolute;
  top: 10%;
  left: 02%;
  display: block;

}
#shift1{
  position: absolute;
  top: 10%;
  left: 02%;
  display: none;
}
#shift2{
  position: absolute;
  top: 10%;
  left: 02%;
  display: none;

}
 .card {
    box-shadow: 0 4px 8px 0 rgba(1,2,3,0.2);
    width: 30%;
}

.container {
    padding: 1px 2px;
    margin: auto;
}

#color{
  background-color: #228B22;
}
#chartContainer{
  position: absolute;
   left:40%;
   top: 20%;}
   #person{
  position: absolute;
   left:35%;
   top: 10%;
   color: black;}
#down{
  position: absolute;
   top: 90%;
   left:10%;
}   
#fun{
  opacity: 0;
  position:absolute;
    left:10%;
}
#fun:hover{
   opacity: 1;
   cursor: pointer;
   position:absolute;
    left:10%;
}
.active{
position:relative;
left:500px;
}
.active1{
position:relative;
left:500px;
}
#look{
  position: absolute;
  left: 10%;
}
#look1{
  position: absolute;
  left: 20%;
}
.remove_list{
 list-style-type: none;
 text-decoration: none; 
}
.notice {
  font-family:arial;
  font-size:100%;
  margin:3em;
  background: #ffff99;
  position: absolute;
  left: 85%;
  text-decoration: none;
  height:16em;
  width:10em;
  padding:1em;
}
#modal-content {
    display: none;
    background-color:#FFFFFF;
    color:#000000;
    margin: auto;
    border-radius: 2px;
    position:absolute;
    left: 580px;
    top: 470px;
    padding: 5px 0;
    width: 200px;
    text-align: center;
    margin-left:0px;
}
#modal-content1 {
    display: none;
    background-color:#FFFFFF;
    color:#000000;
    margin: auto;
    border-radius: 2px;
    position:absolute;
    left: 580px;
    top: 460px;
    padding: 5px 0;
    width: 200px;
    text-align: center;
    margin-left:0px;
}
#orders{
background:   #000000;
}
.close1{
  position: relative;
  left: 50%;
  cursor: pointer;
}
</style>
<body background "https://thumbs.dreamstime.com/z/bull-bear-stock-market-d-illustration-concept-white-background-37382231.jpg">
{% load mathfilters %}
<div id = "shift">
{% for stock in gainer %}
<div class="card">
  <div class="container">
    <p><b>{{ stock.symbol}}</b> &nbsp; &nbsp; &nbsp; <b id="look">{{ stock.netPrice}}%</b> &nbsp; &nbsp; <b id="look1">{{stock.ltp}}</b></p>
    <div id="fun">
<button class="myBtn5">Buy</button>
</div>
  <div id="modal-content1">
  <span class="close1"><b>&times;</b></span>
  <p><b>Price</b><form action="{% url 'daychangers:checkorder' %}"  method="POST" > 
  <input type="radio" name="order" value="market" checked><b> Market </b>
  <input type="radio" name="order" value="limit"><b> limit </b>     
  <input type = "number" step="0.05" name = "quantity" value= "">
 <button name="place" type="submit" value={{stock.symbol}}><a href="{% url 'daychangers:checkorder' %}"></a>BUY</button>
</form></p>
  </div>
</div>
<br>
</div>
{% endfor %}
</div>

<div id="shift1">
{% for stock in loser %}
<div class="card">
  <div class="container">
{% with dif=stock.ltp|sub:stock.previousPrice %}
{% with val=dif|mul:100 %}
{% with final=val|div:stock.previousPrice %}
<p><b>{{ stock.symbol}}</b>&nbsp; &nbsp; &nbsp;<b id="look"> {{final|floatformat:2 }} %</b> &nbsp; &nbsp;<b id="look1"> {{stock.ltp}}</b> </p>
<div id="fun">
<button class="myBtn">Buy</button>
</div>
  <div id="modal-content">
  <span class="close"><b>&times;</b></span>
  <p><b>Price</b><form action="{% url 'daychangers:checkorder' %}"  method="POST" > 
  <input type="radio" name="order" value="market" checked><b> Market </b>
  <input type="radio" name="order" value="limit"><b> limit </b>     
  <input type = "number" step="0.05" name = "quantity" value= "">
 <button name="place" type="submit" value={{stock.symbol}}><a href="{% url 'daychangers:checkorder' %}"></a>BUY</button>
</form></p>
  </div>
</div>
<br>
</div>
{% endwith %}
{% endwith %}
{% endwith %}
{% endfor %}
</div>
<div id = "shift2">
  <div class="ui-widget">
  <label for="tags">Stock: </label>
  <form action="{% url 'daychangers:index' %}" method="POST">
  <input id="tags" type ="text" value="">
  <button id ="select">Add</button>
</form>
</div>
<div class="card">
  <div class="container">
     {% for stock in script %}
    <div id="script_add">
      <p><b>{{ stock.name}}</b> &nbsp; &nbsp; <b id="look">LTP: {{stock.ltp}}</b> </p>
    </div>
      {% endfor %}
  </div>
</div>

</div>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Dashboard &nbsp; &nbsp; &nbsp;</a></li>
      <li class="active1"><a href="{% url 'daychangers:orders' %}">Orderbook &nbsp; &nbsp; &nbsp;</a></li>
      <li class="active1"><a href="{% url 'daychangers:holding' %}">Holdings &nbsp; &nbsp; &nbsp;</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span>{{user}}</a></li>
      <li><a href="{% url 'daychangers:logout_user' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
    </ul>
  </div>
</nav>


<div id="down">
<h4><button id="myBtn1"><b>1</b></button>&nbsp; &nbsp; <button id="myBtn2"><b>2</b></button>&nbsp; &nbsp; <button id="myBtn3"><b>3</b></button></h4>
</div>
</div>
<div id="person"><h2><b>Hi, {{user}}</b></h2></div>
<div id="chartContainer"></div>


<script type="text/javascript">
   {% for check in margin %}
   if ({{check.holdings}} > 0){
  window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer",
    {
      title:{
        text: "Account Value"
      },
      
    
      data: [
      {
       type: "doughnut",
       dataPoints: [
       {  y: {{check.funds}}, indexLabel: "Free Cash" },
       {  y: {{check.holdings}}, indexLabel: "Holdings" },
       ]
     }
     ]

   });

    chart.render();
  }
}
else{
  window.onload = function () {
    var chart = new CanvasJS.Chart("chartContainer",
    {
      title:{
        text: "Account Value"
      },
      
    
      data: [
      {
       type: "doughnut",
       dataPoints: [
       {  y: {{check.funds}}, indexLabel: "Free Cash" },
       ]
     }
     ]
     
   });

    chart.render();
  }
}
{% endfor %}
var btn = document.getElementById("myBtn1");
var btn2 = document.getElementById("myBtn2");
var btn3 = document.getElementById("myBtn3");
var tab1=document.getElementById("shift");
var tab2=document.getElementById("shift1");
var tab3=document.getElementById("shift2");
var add=document.getElementById("select");

btn.onclick = function(){
  tab1.style.display = "block";
  tab2.style.display ="none";
  tab3.style.display ="none";
}
btn2.onclick = function(){
  tab2.style.display = "block";
  tab1.style.display ="none";
  tab3.style.display ="none";
}
btn3.onclick = function(){
  tab3.style.display ="block";
  tab2.style.display = "none";
  tab1.style.display ="none";
}
document.getElementById("select").addEventListener("click", function(event){
    event.preventDefault()
    var searchTerm = $('#tags').val();
    var li = document.createElement("li"); 
    $.ajax({
    url: 'https://gainerandloser.herokuapp.com/addsymbol/',
    data: { stock:searchTerm} ,
    type: 'GET',
    dataType : "json",
    success: function(data) {
      var li = document.createElement("li");
      li.className = "remove_list";
      li.innerHTML=searchTerm+" " +"LTP:"+data;
      document.getElementById("script_add").appendChild(li);
        },
}); 

});
var btn = document.getElementsByClassName("myBtn");
var btn5 = document.getElementsByClassName("myBtn5");
var che = document.getElementById("modal-content");
var che1 = document.getElementById("modal-content1");
var span = document.getElementsByClassName("close")[0];
var span1 = document.getElementsByClassName("close1")[0];

for(var i=0;i<btn.length;i++){
 btn[i].onclick = function(){
 che.style.display = "block";
}
}
for(var i=0;i<btn5.length;i++){
 btn5[i].onclick = function(){
 che1.style.display = "block";
}
}
span1.onclick=function(){
  che1.style.display = "none";
}

span.onclick=function(){
  che.style.display = "none";
}
$( function() {
    var availableTags = ['WIPRO','RELIANCE','ZEEL','COALINDIA','KOTAKBANK','TCS','AMBUJACEM','IOC','HCLTECH','INFY','INFRATEL','TATAMOTORS','TECHM','ICICIBANK','ULTRACEMCO','TATAMTRDVR',
        'ADANIPORTS','INDUSINDBK','MARUTI','TATAPOWER','HINDUNILVR','YESBANK','HINDALCO','DRREDDY','AXISBANK','ASIANPAINT','BPCL','SBIN','BANKBARODA','ACC','BAJAJ-AUTO','NTPC','ITC','VEDL','HDFCBANK','GAIL','BOSCHLTD','HDFC','LT',
        'AUROPHARMA','M&M','ONGC','TATASTEEL','CIPLA','SUNPHARMA','EICHERMOT','LUPIN','POWERGRID','IBULHSGFIN','BHARTIARTL'];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );

  </script>
  <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>


</body>
</html>

daychangers/templates/daychangers/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

daychangers/templates/daychangers/holding.html
<!DOCTYPE html>
<html>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
}
th {
    text-align: left;
}
.changes{
position: absolute;
left: 80%;
text-decoration: none;
background: #ffff99;
}
table{border-spacing: 1; 
  border-collapse: collapse; 
  background:white;
  border-radius:6px;
  overflow:hidden;
  max-width:800px; 
  width:100%;
  margin:0 auto;
  position:relative;
height:60px;
    background:#FFED86;
    font-size:16px;}
    h2{
position: relative;
left: 50%;
} 
</style>
{% load mathfilters %}

<table>
<tr>
	<td><b>Date</b></td>
	<td><b>Symbol</b></td>
	<td><b>Price</b></td>
	<td><b>Quantity</b></td>
	<td><b>LTP</b></td>
	<td><b>P&L</b></td>
</tr>
{% for q1 in i_d %}
<tr>
	<td>{{q1.date}}</td>
	<td>{{q1.symbol}}</td>
	<td>{{q1.price}}</td>
	<td>{{q1.quantity}}</td>
	<td>{{detail.lastPrice}}</td>
	{% with dif=q1.price|sub:detail.lastPrice %}
	<td>{{dif}}</td>	
	{% endwith %}
</tr>	
{% endfor %}
</table>
<h2>{{msg}}</h2>
<div class="changes">
<p><a href="{% url 'daychangers:index' %}">Click here</a> &nbsp; to go back to dashboard page</p> 
</div>
</html>

daychangers/templates/daychangers/index.html
<html>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
.subject{position: absolute;top: 25%; left: 34%;list-style-type: none;background:#90EE90;
    padding: 70px;text-decoration: none;
}
ul li{background:#FFFFF0;}
a:link {
    text-decoration: none;
}
a:hover{ background: #F0E68C;

}
p {
  font-family:arial;
  font-size:100%;
  margin:3em;
  background: #ffff99;
  position: absolute;
  left: 70%;
  text-decoration: none;
  height:8em;
  width:14em;
  padding:1em;
}
.location{position: absolute;left: 92%; top:01%;}

</style>
<body background = "http://www.lintex.com.au/wp-content/uploads/2017/01/Stock-Image-9.jpg">

  <ul class = "subject">
    <h2><li><strong><a href="{% url 'daychangers:search' %}">Get Stock quotes</a></strong></li></h2><br>
    <h2><li><strong><a href="{% url 'daychangers:supergainer' %}">Today Top 10 Gainer</a></strong></li></h2><br> 
    <h2><li><strong><a href="{% url 'daychangers:superloser' %}">Today Top 10 Loser</a></strong></li></h2><br>
    <h2><li><strong><a href="http://pulse.zerodha.com/">Read latest news</a></strong></li></h2>

  </ul>
  <button type="button" class="location">
          <span class="glyphicon glyphicon-log-out"></span><a href="{% url 'daychangers:login_user' %}"> Log out</a>
        </button>

<p>If any feature request/suggestion, please ping me at rakesh.ranjan@zerodha.com</p>

</body>     
</html>

daychangers/templates/daychangers/login.html
<html>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
<style>
.container-fluid{
    width: 300px;
    border: 25px;
    margin: 25px;
position: absolute;
   left:30%;
   top: 10%;}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'daychangers:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                  Don't have an account? <a href="{% url 'daychangers:register' %}">Click here</a> to register  
                    <br>
                    <br>
                </div>               
            </div>
        </div>
    </div>

</div>

</html>

daychangers/templates/daychangers/redlogin.html
<html>
<style>
.redirect{position: absolute;
   left:30%;
   top: 10%;
font: italic;}
</style>

<div class='redirect'>
<h3><a href="{% url 'daychangers:login_user'%}">Please<strong>  Click here </strong></a> to login.</h3>
</div>

</html>

daychangers/templates/daychangers/stocklist.html
<html>
{% for stock in stockli %}
<p>{{stock}}</p>
{% endfor %}

</html>